@startuml

title Процесс обмена через брокер (consumer)

start
:Инициализация консюмера;

if (Успех?) then (Да)
    : Подписка на топик;
    If (Успех?) then (Да)
        repeat
            : Получить 1000 сообщений;
            If (Успех?) then (Да)
                If (Есть сообщения?) then (Да)
                    #palegreen: Подтвердить получение;
                    #palegreen: Записать сообщения;
                    note right: Справочник "Входящие сообщения"
                    if (Макс. длительность\nпроцесса превышает заданную?) then (Да)
                        note right: Определяется константой
                        : Отключение консюмера;
                        stop
                    else (Нет)
                        : Продолжение процесса;
                    endif
                else (Нет)
                    : Отключение консюмера;
                    stop
                endif
            else (Нет)
                : Отключение консюмера;
                #pink: Запись в журнале регистрации;
                stop
            endif
        repeat while (Истина?) is (Да)
    else (Нет)
        : Отключение консюмера;
        #pink: Запись в журнале регистрации;
        stop
    endif
else (Нет)
    #pink: Запись в журнале регистрации;
    stop
endif
stop

@enduml