@startuml

title Процесс обмена через брокер (producer)

start
:Инициализация продюсера;

if (Успех?) then (Да)
    repeat
        : Выборка 1000 сообщений
        ----
        Выполнена сериализация
        Попыток отправки < 10
        Дата следующей отправки <= Текущая дата;
        if (Есть сообщения?) then (Да)
            : Подготовка пула JSON-сообщений;
            if (Успех?) then (Да)
                : Отправка сообщений в брокер;
                while (Есть необработанные отчеты о доставке?) is (Да)
                    if (Сообщение доставлено) then (Да)
                        #palegreen: Создание исходящего сообщения;
                        #palegreen: Удаление сообщения из очереди;
                    else (Нет)
                        #pink: Фиксация ошибки;
                        : Увеличение количества попыток;
                        : Расчет даты следующей попытки
                        ----
                        Текущая дата + Период повторной отправки;
                        : Обновление записи очереди;
                    endif
                endwhile (Нет)
            else (Нет)
                : Отключение продюсера;
                #pink: Запись в журнале регистрации;
                stop
            endif
        else (Нет)
            : Отключение продюсера;
            stop
        endif
    repeat while (Истина?) is (Да)
else (Нет)
    #pink: Запись в журнале регистрации;
    stop
endif
stop

@enduml