@startuml

!include C:/Repo/1ce-icons-for-plantuml/dist/common.puml
!include C:/Repo/1ce-icons-for-plantuml/dist/all.puml

title Схема метаданных

package ЭкспортДанныхБУ <<folder>> {
    _Документ(ДокументСсылка, "ДокументСсылка") {
        Номер
        Дата
        ...
    }

    _Документ(ОперацияКОтражениюВУпрУчете, "ОперацияКОтражениюВУпрУчете") {
        Номер
        Дата
        ПервичныйДокумент
    }

    _РегистрСведений(ОчередьСообщений, "ОчередьСообщений") {
        <$d> Топик
        <$d> Объект
        <$d> ДатаДобавления
        <$r> ТекстСообщения
        ОшибкиСериализации
        ОшибкиОтправки
        ПопытокОтправки
        ДатаСледующейОтправки
    }

    _Справочник(ИсходящиеСообщения, "ИсходящиеСообщения") {
        Код (Ключ)
        Топик
        Партиция
        Смещение
        Объект
        ДатаОтправки
        ТекстСообщения
    }
}

package ИмпортДанныхБУ <<folder>> {

    _Справочник(ВходящиеСообщения, "ВходящиеСообщения") {
        Код (Ключ)
        Топик
        Партиция
        Смещение
        Сообщение
        ДатаПолучения
        Объект
        ОшибкиОбработки
        ПопытокОбработки
        ДатаСледующейОбработки
    }

    _Документ(ОперацияБух, "ОперацияБух") {
        Номер
        Дата
        Организация
        Содержание
        СуммаОперации
        Комментарий
    }
}

ДокументСсылка --> ОперацияКОтражениюВУпрУчете::ПервичныйДокумент
ОперацияКОтражениюВУпрУчете --> ОчередьСообщений::Объект
ОперацияКОтражениюВУпрУчете --> ИсходящиеСообщения::Объект
ОперацияБух --> ВходящиеСообщения::Объект

@enduml